apiVersion: apps/v1
kind: Deployment
metadata:
  name: projapp
  labels: 
    app: projapp
spec:
  selector:
    matchLabels:
      app: projapp
  replicas: 1    
  template:
    metadata:
      labels:
        app: projapp
    spec:
      containers:
        - name: projapp
          image: olajaido/vprofileapp:V1
          ports:
            - name: projapp-port
              containerPort: 8080
      initContainers: 
        - name: init-mydb
          image: busybox
          command: ['sh', '-c', 'until nslookup projdb; do echo waiting for mydb; sleep 2; done;']
        - name: init-memcache
          image: busybox
          command: ['sh', '-c', 'until nslookup projmc; do echo waiting for cache; sleep 2; done;']      
        
