apiVersion: apps/v1
kind: Deployment
metadata:
  name: projapp
  labels: 
    app: projapp
spec:
  selector:
    matchLabels:
      app: projapp
  replicas: 1    
  template:
    metadata:
      labels:
        app: projapp
    spec:
      containers:
        - name: projapp
          image: olajaido/vprofileapp:V1
          ports:
            - name: projapp-port
              containerPort: 8080
          
        
