apiVersion: apps/v1
kind: Deployment
metadat: 
  name: projrmq01
  labels: 
    app: projrmq01
spec: 
  selector:
    matchLabels:
      app: projrmq01
  replicas: 1
  template: 
    metadata:
      labels:
        app: projrmq01
    spec: 
      containers:
        - name: projrmq01
          image:  rabbitmq
          ports:
            - name: projrmq01-port  
              containerPort: 15672
          env: 
            - name: RABBITMQ_DEFAULT_PASS
              valueFromRef: 
                name: app-secret
                key: rmq-pass
            - name: RABBITMQ_DEFAULT_USER
              value: "guest"    

              